
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('catalogo.paises').del()
    .then(function () {
      // Inserts seed entries
      return knex('catalogo.paises').insert([
        { codigoInternacional: '101', codigoNacional: '2', descripcion: 'Albania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '102', codigoNacional: '14', descripcion: 'Austria', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '103', codigoNacional: '20', descripcion: 'Bélgica', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '104', codigoNacional: '31', descripcion: 'Bulgaria', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '106', codigoNacional: '42', descripcion: 'Chipre', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '107', codigoNacional: '53', descripcion: 'Dinamarca', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '108', codigoNacional: '64', descripcion: 'España', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '109', codigoNacional: '71', descripcion: 'Finlandia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '110', codigoNacional: '72', descripcion: 'Francia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '111', codigoNacional: '79', descripcion: 'Grecia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '112', codigoNacional: '93', descripcion: 'Hungría', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '113', codigoNacional: '98', descripcion: 'Irlanda', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '114', codigoNacional: '101', descripcion: 'Islandia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '115', codigoNacional: '116', descripcion: 'Italia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '116', codigoNacional: '132', descripcion: 'Liechtenstein', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '117', codigoNacional: '134', descripcion: 'Luxemburgo', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '118', codigoNacional: '141', descripcion: 'Malta', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '119', codigoNacional: '149', descripcion: 'Mónaco', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '120', codigoNacional: '162', descripcion: 'Noruega', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '121', codigoNacional: '166', descripcion: 'Países Bajos', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '122', codigoNacional: '175', descripcion: 'Polonia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '123', codigoNacional: '176', descripcion: 'Portugal', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '124', codigoNacional: '4', descripcion: 'Andorra', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '125', codigoNacional: '179', descripcion: 'Reino Unido', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '126', codigoNacional: '3', descripcion: 'Alemania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '128', codigoNacional: '189', descripcion: 'Rumanía', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '129', codigoNacional: '198', descripcion: 'San Marino', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '130', codigoNacional: '242', descripcion: 'Santa Sede', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '131', codigoNacional: '216', descripcion: 'Suecia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '132', codigoNacional: '217', descripcion: 'Suiza', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '135', codigoNacional: '232', descripcion: 'Ucrania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '136', codigoNacional: '128', descripcion: 'Letonia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '137', codigoNacional: '183', descripcion: 'Moldavia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '138', codigoNacional: '243', descripcion: 'Belarús', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '139', codigoNacional: '75', descripcion: 'Georgia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '141', codigoNacional: '67', descripcion: 'Estonia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '142', codigoNacional: '133', descripcion: 'Lituania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '143', codigoNacional: '182', descripcion: 'República Checa', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '144', codigoNacional: '62', descripcion: 'República Eslovaca', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '145', codigoNacional: '27', descripcion: 'Bosnia y Herzegovina', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '146', codigoNacional: '50', descripcion: 'Croacia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '147', codigoNacional: '63', descripcion: 'Eslovenia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '148', codigoNacional: '11', descripcion: 'Armenia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '154', codigoNacional: '190', descripcion: 'Rusia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '156', codigoNacional: '126', descripcion: 'Macedonia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '157', codigoNacional: '206', descripcion: 'Serbia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '158', codigoNacional: '151', descripcion: 'Montenegro', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '199', codigoNacional: '994', descripcion: 'Otros países de Europa', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '201', codigoNacional: '32', descripcion: 'Burkina Faso', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '202', codigoNacional: '5', descripcion: 'Angola', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '203', codigoNacional: '9', descripcion: 'Argelia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '204', codigoNacional: '22', descripcion: 'Benin', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '205', codigoNacional: '28', descripcion: 'Botswana', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '206', codigoNacional: '33', descripcion: 'Burundi', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '207', codigoNacional: '244', descripcion: 'Cabo Verde', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '208', codigoNacional: '37', descripcion: 'Camerún', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '209', codigoNacional: '245', descripcion: 'Comores', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '210', codigoNacional: '45', descripcion: 'Congo', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '211', codigoNacional: '48', descripcion: 'Costa de Marfil', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '212', codigoNacional: '54', descripcion: 'Djibouti', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '213', codigoNacional: '57', descripcion: 'Egipto', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '214', codigoNacional: '68', descripcion: 'Etiopía', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '215', codigoNacional: '73', descripcion: 'Gabón', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '216', codigoNacional: '74', descripcion: 'Gambia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '217', codigoNacional: '76', descripcion: 'Ghana', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '218', codigoNacional: '87', descripcion: 'Guinea', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '219', codigoNacional: '88', descripcion: 'Guinea-Bissau', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '220', codigoNacional: '86', descripcion: 'Guinea Ecuatorial', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '221', codigoNacional: '246', descripcion: 'Kenia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '222', codigoNacional: '247', descripcion: 'Lesotho', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '223', codigoNacional: '130', descripcion: 'Liberia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '224', codigoNacional: '131', descripcion: 'Libia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '225', codigoNacional: '136', descripcion: 'Madagascar', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '226', codigoNacional: '138', descripcion: 'Malawi', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '227', codigoNacional: '140', descripcion: 'Mali', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '228', codigoNacional: '142', descripcion: 'Marruecos', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '229', codigoNacional: '144', descripcion: 'Mauricio', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '230', codigoNacional: '145', descripcion: 'Mauritania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '231', codigoNacional: '153', descripcion: 'Mozambique', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '232', codigoNacional: '155', descripcion: 'Namibia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '233', codigoNacional: '159', descripcion: 'Níger', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '234', codigoNacional: '160', descripcion: 'Nigeria', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '235', codigoNacional: '181', descripcion: 'República Centroafricana', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '236', codigoNacional: '213', descripcion: 'Sudáfrica', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '237', codigoNacional: '248', descripcion: 'Ruanda', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '238', codigoNacional: '203', descripcion: 'Santo Tomé y Príncipe', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '239', codigoNacional: '205', descripcion: 'Senegal', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '240', codigoNacional: '207', descripcion: 'Seychelles', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '241', codigoNacional: '208', descripcion: 'Sierra Leona', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '242', codigoNacional: '211', descripcion: 'Somalia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '243', codigoNacional: '214', descripcion: 'Sudán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '244', codigoNacional: '220', descripcion: 'Swazilandia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '245', codigoNacional: '187', descripcion: 'Tanzania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '246', codigoNacional: '39', descripcion: 'Chad', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '247', codigoNacional: '224', descripcion: 'Togo', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '248', codigoNacional: '228', descripcion: 'Túnez', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '249', codigoNacional: '233', descripcion: 'Uganda', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '250', codigoNacional: '184', descripcion: 'República Democrática del Congo', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '251', codigoNacional: '240', descripcion: 'Zambia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '252', codigoNacional: '241', descripcion: 'Zimbabwe', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '253', codigoNacional: '61', descripcion: 'Eritrea', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '254', codigoNacional: '215', descripcion: 'Sudán del Sur', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '299', codigoNacional: '995', descripcion: 'Otros países de África', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '301', codigoNacional: '38', descripcion: 'Canadá', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '302', codigoNacional: '66', descripcion: 'Estados Unidos de América', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '303', codigoNacional: '147', descripcion: 'México', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '310', codigoNacional: '7', descripcion: 'Antigua y Barbuda', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '311', codigoNacional: '16', descripcion: 'Bahamas', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '312', codigoNacional: '19', descripcion: 'Barbados', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '313', codigoNacional: '21', descripcion: 'Belice', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '314', codigoNacional: '49', descripcion: 'Costa Rica', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '315', codigoNacional: '51', descripcion: 'Cuba', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '316', codigoNacional: '55', descripcion: 'Dominica', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '317', codigoNacional: '58', descripcion: 'El Salvador', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '318', codigoNacional: '78', descripcion: 'Granada', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '319', codigoNacional: '83', descripcion: 'Guatemala', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '320', codigoNacional: '90', descripcion: 'Haití', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '321', codigoNacional: '91', descripcion: 'Honduras', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '322', codigoNacional: '117', descripcion: 'Jamaica', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '323', codigoNacional: '158', descripcion: 'Nicaragua', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '324', codigoNacional: '169', descripcion: 'Panamá', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '325', codigoNacional: '200', descripcion: 'San Vicente y las Granadinas', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '326', codigoNacional: '186', descripcion: 'República Dominicana', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '327', codigoNacional: '227', descripcion: 'Trinidad y Tobago', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '328', codigoNacional: '202', descripcion: 'Santa Lucía', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '329', codigoNacional: '197', descripcion: 'San Cristóbal y Nieves', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '340', codigoNacional: '10', descripcion: 'Argentina', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '341', codigoNacional: '25', descripcion: 'Bolivia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '342', codigoNacional: '29', descripcion: 'Brasil', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '343', codigoNacional: '43', descripcion: 'Colombia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '344', codigoNacional: '40', descripcion: 'Chile', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '345', codigoNacional: '56', descripcion: 'Ecuador', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '346', codigoNacional: '89', descripcion: 'Guyana', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '347', codigoNacional: '171', descripcion: 'Paraguay', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '348', codigoNacional: '172', descripcion: 'Perú', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '349', codigoNacional: '218', descripcion: 'Surinam', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '350', codigoNacional: '234', descripcion: 'Uruguay', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '351', codigoNacional: '237', descripcion: 'Venezuela', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '399', codigoNacional: '996', descripcion: 'Otros países de América', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '401', codigoNacional: '1', descripcion: 'Afganistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '402', codigoNacional: '8', descripcion: 'Arabia Saudí', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '403', codigoNacional: '17', descripcion: 'Bahréin', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '404', codigoNacional: '18', descripcion: 'Bangladesh', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '405', codigoNacional: '154', descripcion: 'Myanmar', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '407', codigoNacional: '41', descripcion: 'China', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '408', codigoNacional: '60', descripcion: 'Emiratos Árabes Unidos', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '409', codigoNacional: '70', descripcion: 'Filipinas', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '410', codigoNacional: '94', descripcion: 'India', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '411', codigoNacional: '95', descripcion: 'Indonesia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '412', codigoNacional: '96', descripcion: 'Iraq', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '413', codigoNacional: '97', descripcion: 'Irán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '414', codigoNacional: '115', descripcion: 'Israel', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '415', codigoNacional: '118', descripcion: 'Japón', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '416', codigoNacional: '120', descripcion: 'Jordania', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '417', codigoNacional: '36', descripcion: 'Camboya', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '418', codigoNacional: '125', descripcion: 'Kuwait', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '419', codigoNacional: '185', descripcion: 'Laos', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '420', codigoNacional: '129', descripcion: 'Líbano', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '421', codigoNacional: '137', descripcion: 'Malasia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '422', codigoNacional: '139', descripcion: 'Maldivas', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '423', codigoNacional: '150', descripcion: 'Mongolia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '424', codigoNacional: '157', descripcion: 'Nepal', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '425', codigoNacional: '165', descripcion: 'Omán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '426', codigoNacional: '167', descripcion: 'Pakistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '427', codigoNacional: '178', descripcion: 'Qatar', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '430', codigoNacional: '47', descripcion: 'Corea del Sur', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '431', codigoNacional: '46', descripcion: 'Corea del Norte', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '432', codigoNacional: '209', descripcion: 'Singapur', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '433', codigoNacional: '180', descripcion: 'Siria', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '434', codigoNacional: '212', descripcion: 'Sri Lanka', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '435', codigoNacional: '221', descripcion: 'Tailandia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '436', codigoNacional: '230', descripcion: 'Turquía', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '437', codigoNacional: '238', descripcion: 'Vietnam', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '439', codigoNacional: '249', descripcion: 'Brunei', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '440', codigoNacional: '109', descripcion: 'Islas Marshall', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '441', codigoNacional: '239', descripcion: 'Yemen', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '442', codigoNacional: '15', descripcion: 'Azerbaiyán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '443', codigoNacional: '121', descripcion: 'Kazajstán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '444', codigoNacional: '123', descripcion: 'Kirguistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '445', codigoNacional: '250', descripcion: 'Tayikistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '446', codigoNacional: '229', descripcion: 'Turkmenistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '447', codigoNacional: '235', descripcion: 'Uzbekistán', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '448', codigoNacional: '251', descripcion: 'Bhután', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '449', codigoNacional: '65', descripcion: 'Palestina. Estado Observador, no miembro de Naciones Unidas', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '499', codigoNacional: '997', descripcion: 'Otros países de Asia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '501', codigoNacional: '13', descripcion: 'Australia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '502', codigoNacional: '252', descripcion: 'Fiji', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '504', codigoNacional: '164', descripcion: 'Nueva Zelanda', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '505', codigoNacional: '170', descripcion: 'Papúa Nueva Guinea', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '506', codigoNacional: '110', descripcion: 'Islas Salomón', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '507', codigoNacional: '195', descripcion: 'Samoa', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '508', codigoNacional: '226', descripcion: 'Tonga', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '509', codigoNacional: '236', descripcion: 'Vanuatu', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '511', codigoNacional: '148', descripcion: 'Micronesia', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '512', codigoNacional: '231', descripcion: 'Tuvalu', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '513', codigoNacional: '104', descripcion: 'Islas Cook', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '514', codigoNacional: '124', descripcion: 'Kiribati', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '515', codigoNacional: '156', descripcion: 'Nauru', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '516', codigoNacional: '253', descripcion: 'Palaos', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '517', codigoNacional: '254', descripcion: 'Timor Oriental', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }, 
{ codigoInternacional: '599', codigoNacional: '998', descripcion: 'Otros países de Oceanía', idEstadosRegistro: 2, idCredenciales_ingreso: 1 }
      ]);
    });
};
